#!/usr/bin/env bash
# Regenerate THIRD_PARTY_NOTICES.md from the module graph, the vendored
# tree-sitter grammars, and the bundled data sets. CI re-runs this and fails if
# the result differs from the committed file, so the notices cannot go stale.
#
#   scripts/gen-third-party-notices.sh
#
# Requires go-licenses for the module table:
#   go install github.com/google/go-licenses@latest
set -euo pipefail

# The module sits under go/ in the development repository and at the root in the
# published one, so find it rather than assuming a depth. The notices file always
# belongs at the repository root, which is the module root unless the module is
# nested inside it.
here="$(cd "$(dirname "$0")" && pwd)"
MODULE_ROOT="$here"
while [ ! -f "$MODULE_ROOT/go.mod" ]; do
  parent="$(dirname "$MODULE_ROOT")"
  [ "$parent" = "$MODULE_ROOT" ] && { echo "error: no go.mod above $here" >&2; exit 1; }
  MODULE_ROOT="$parent"
done
REPO_ROOT="$MODULE_ROOT"
while [ ! -d "$REPO_ROOT/.git" ]; do
  parent="$(dirname "$REPO_ROOT")"
  [ "$parent" = "$REPO_ROOT" ] && { REPO_ROOT="$MODULE_ROOT"; break; }
  REPO_ROOT="$parent"
done

cd "$MODULE_ROOT"
OUT="$REPO_ROOT/THIRD_PARTY_NOTICES.md"

# Paths quoted in the notices are relative to the repository root, so the grammar
# directory gains a go/ prefix only where the module is nested.
PREFIX=""
[ "$MODULE_ROOT" != "$REPO_ROOT" ] && PREFIX="$(basename "$MODULE_ROOT")/"

{
  echo "# Third-party notices"
  echo
  echo "VyQL bundles and depends on the components below."
  echo
  echo "Generated by scripts/gen-third-party-notices.sh — do not edit by hand."
  echo
  echo "## Vendored tree-sitter grammars"
  echo
  echo "Compiled into the binary from C sources committed under"
  echo "\`${PREFIX}extract/frontend/treesitter/grammars/\`. Each directory carries its"
  echo "upstream LICENSE verbatim."
  echo
  echo "| Grammar | Upstream | License |"
  echo "|---|---|---|"
  echo "| dart | github.com/UserNobody14/tree-sitter-dart | MIT |"
  echo "| elixir | github.com/elixir-lang/tree-sitter-elixir | Apache-2.0 |"
  echo "| groovy | github.com/murtaza64/tree-sitter-groovy | MIT |"
  echo "| objc | github.com/tree-sitter-grammars/tree-sitter-objc | MIT |"
  echo "| perl | github.com/tree-sitter-perl/tree-sitter-perl | MIT |"
  echo "| powershell | github.com/airbus-cert/tree-sitter-powershell | MIT |"
  echo "| solidity | github.com/JoranHonig/tree-sitter-solidity | MIT |"
  echo "| swift | github.com/alex-pinkus/tree-sitter-swift | MIT |"
  echo
  echo "Grammars with usable upstream Go bindings are ordinary module"
  echo "dependencies and appear in the module table below instead."
  echo
  echo "## Bundled data"
  echo
  echo "### MITRE CWE and CAPEC"
  echo
  echo "\`vyql/taxonomy/cwe.json\` and \`vyql/taxonomy/capec.json\` derive from the"
  echo "MITRE CWE and CAPEC catalogs."
  echo
  echo "Copyright (c) 2006-2026, The MITRE Corporation. All rights reserved."
  echo "CWE and CAPEC are trademarks of The MITRE Corporation."
  echo
  echo "Full notice: \`vyql/taxonomy/ATTRIBUTION.md\`."
  echo
  echo "### ecosyste.ms package rankings"
  echo
  echo "\`vyql/bindings/packages/top1000.snapshot.json\` is generated by"
  echo "\`${PREFIX}scripts/fetch-package-top1000.mjs\` from the ecosyste.ms packages API"
  echo "(https://packages.ecosyste.ms). It records package names, registries and"
  echo "popularity counts — factual data only, no descriptive text."
  echo
  echo "ecosyste.ms data is published under CC-BY-SA 4.0"
  echo "(https://creativecommons.org/licenses/by-sa/4.0/). That attribution and"
  echo "share-alike obligation applies to this snapshot file specifically. The"
  echo "file is build and test input; it is not loaded at scan time."
  echo
  echo "## Go module dependencies"
  echo
  if command -v go-licenses >/dev/null 2>&1; then
    # go-licenses lists this module's own packages alongside real dependencies.
    # They are first-party code covered by this repo's own LICENSE, so filter them
    # out — a third-party notice that claims your own packages is simply wrong.
    self="$(go list -m)"
    echo "| Module | License |"
    echo "|---|---|"
    go-licenses report ./... --template /dev/stdin <<'TPL' 2>/dev/null \
      | grep -v "^| ${self}" | grep -v '^[[:space:]]*$' | sort -u || \
      echo "(go-licenses failed; re-run locally to refresh this table)"
{{range .}}| {{.Name}} | {{.LicenseName}} |
{{end}}
TPL
  else
    echo "(go-licenses not installed; run: go install github.com/google/go-licenses@latest)"
  fi
} > "$OUT"

echo "wrote $OUT"
